/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'stephenmolloy' at '3/18/16 3:58 PM' with Gradle 2.9
 *
 * @author stephenmolloy, @date 3/18/16 3:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
